# Пермишены:
#  win.bypass - обход ограничений
#  win.help - /win help
#  win.reload - /win reload
#  win.top - /win top
#  win.money - /win money
#  win.invest - /win invest
#  win.withdraw - /win withdraw
#  win.info - /win info
#  win.rules - /win rules
#  win.prize - /win prize

database:
  isMySQL: false # false - SQLite, true - MySQL
  host: localhost
  port: 3306
  database: db
  user: root
  password: root

settings:
  # Настройка лимита
  limit:
    enabled: true
    time: 86400000 # Время в миллисекундах
    amount: 25000000 # Сколько можно вложить за указанное время

  features:
    winTop: false
    winMoney: true
    winInvest: true
    winWithdraw: false

messages:
  onlyPlayer:
    - "Эта команда только для игроков!"


  winHelp:
    perm:
      - "&f> &#fb7e00Недостаточно прав!"

    success:
      - "&#fb7e00Справка по командам WIN-Топа"
      - "&f> &#fb7e00/win help &f- Получить справку помощи"
      - "&f> &#fb7e00/win top &f- Посмотреть ТОП по игрокам"
      - "&f> &#fb7e00/win money &f- Посмотреть свой баланс"
      - "&f> &#fb7e00/win invest сумма &f- Вложить деньги"
      - "&f> &#fb7e00/win withdraw сумма &f- Снять деньги"
      - "&f> &#fb7e00/win info &f- Посмотреть условия и инфу"
      - "&f> &#fb7e00/win rules &f- Правила конкурса"
      - "&f> &#fb7e00/win prize &f- Посмотреть призы за ТОП"

  winReload:
    perm:
      - "&f> &#fb7e00Недостаточно прав!"
    usage:
      - "&f> &#fb7e00Используйте &e/win reload"
    success:
      - "&f> &#fb7e00Плагин перезагружен!"

  winTop:
    perm:
      - "&f> &#fb7e00Недостаточно прав!"
    disabled:
      - "&cВнимание! &#fb7e00Сейчас ТОП отключен."
      - "&#fb7e00Вы не будете видеть как развиваются конкуренты."
      - "&#fb7e00Топ будет включен в конце конкурса."
    defaultName: "<нет>" # Если на указанном месте в топе никого нет
    defaultBalance: "&e<нет>" # Если на указанном месте в топе никого нет
    decimalFormat: "&e$#,###" # Формат для чисел
    success:
      - "&#fb7e00ТОП игроков:"
      - "%top%"
    topLines:
      - "&f[1] &#fb7e00%player%&f : %balance%"
      - "&f[2] &#fb7e00%player%&f : %balance%"
      - "&f[3] &#fb7e00%player%&f : %balance%"
      - "&f[4] &#fb7e00%player%&f : %balance%"
      - "&f[5] &#fb7e00%player%&f : %balance%"
      - "&f[6] &#fb7e00%player%&f : %balance%"
      - "&f[7] &#fb7e00%player%&f : %balance%"
      - "&f[8] &#fb7e00%player%&f : %balance%"
      - "&f[9] &#fb7e00%player%&f : %balance%"
      - "&f[10] &#fb7e00%player%&f : %balance%"

  winMoney:
    perm:
      - "&f> &#fb7e00Недостаточно прав!"
    disabled:
      - "&5[$] &#fb7e00На данный момент просматривать баланс нельзя!"
    decimalFormat: "$#,###" # Формат для чисел
    success:
      - "&5[$] &fВаш баланс WIN Топа: &#fb7e00%balance%"

  winInvest:
    perm:
      - "&f> &#fb7e00Недостаточно прав!"
    disabled:
      - "&5[$] &#fb7e00На данный момент вкладывать деньги нельзя!"
    numberError:
      - "&5[$] &#fb7e00Сумма должна быть числом и больше нуля!"
    balanceError:
      - "&5[$] &#fb7e00Недостаточно денег на балансе для пополнения!"
    limit:
      - "&5[$] &#fb7e00Эта сумма превышает дневной лимит!"
    success:
      - "&5[$] &#fb7e00Вы успешно пополнили баланс WIN Топа!"

  winWithdraw:
    perm:
      - "&f> &#fb7e00Недостаточно прав!"
    disabled:
      - "&5[$] &#fb7e00На данный момент снимать деньги нельзя!"
    numberError:
      - "&5[$] &#fb7e00Сумма должна быть числом и больше нуля!"
    amountError:
      - "&5[$] &#fb7e00Сумма должна быть меньше баланса WIN Топа!"
    success:
      - "&5[$] &#fb7e00Вы успешно сняли баланс WIN Топа!"

  winInfo:
    perm:
      - "&f> &#fb7e00Недостаточно прав!"

    success:
      - "&cИНФО: &#fb7e00Конкурс по ТОП Баланса игроков."
      - "&cУсловия:"
      - "&c> &fНикто не знает ТОП до конца конкурса;"
      - "&c> &fСнять вложенные средства невозможно;"
      - "&c> &fПриз не может делиться на тиммейтов;"
      - "&c> &fПолные правила в группе ВК"
      - "&cКонец конкурса: &#fb7e00неизвестно"

  winRules:
    perm:
      - "&f> &#fb7e00Недостаточно прав!"

    success:
      - "&cПравила: &#fb7e00Для участников конкурса"
      - "&c> &fПринять участие можно лишь на одном режиме;"
      - "&c> &fНельзя принимать участие с мультиаккаунтов;"
      - "&c> &fНельзя как либо пытаться обойти систему;"
      - "&c> &fЕсли за вайп вы/ваш мультиаккаунт был забанен по серьёзно причине - дисквалификация;"
      - "&c> &fЕсли ваши тиммейты  были забанены по серьёзной причине - дисквалификация;"

  winPrize:
    perm:
      - "&f> &#fb7e00Недостаточно прав!"

    success:
      - "&cИНФО: &#fba700Конкурс по ТОП Баланса игроков."
      - "&#fb7e00Призы на Анархии:"
      - " &#f8fb87[1] Место: &#46fb6575,000 Токенов!"
      - " &#f8fb87[2] Место: &#46fb6560,000 Токенов!"
      - " &#f8fb87[3] Место: &#46fb6550,000 Токенов!"
      - " &#f8fb87[4] Место: &#46fb6535,000 Токенов!"
      - " &#f8fb87[5] Место: &#46fb6525,000 Токенов!"
      - "&#fb7e00Призы на Гриферском:"
      - " &#f8fb87[1] Место: &#46fb6535,000 Токенов!"
      - " &#f8fb87[2] Место: &#46fb6515,000 Токенов!"
      - " &#f8fb87[3] Место: &#46fb6515,000 Токенов!"